services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_EMAIL
        value: tucorreo@gmail.com
      - key: BOT_EMAIL_PASSWORD
        value: tu_contraseña_de_aplicación
      - key: BOT_TOKEN
        value: tu_token_de_telegram
